import { test, expect } from '@playwright/test';
import { BrokerFixture, stored } from './support/broker';

for (const standalone of [false, true]) {
  test(`${standalone ? 'standalone' : 'development'} summary matches explicit execution rules and validates price ticks`, async ({ page }) => {
    const broker = new BrokerFixture(); await broker.install(page, standalone); await broker.connected(page);
    const ticket = page.locator('.order-ticket'), summary = ticket.getByRole('region', { name: 'Order summary', exact: true });
    const row = (label: string) => summary.locator('dl > div').filter({ has: page.locator('dt', { hasText: new RegExp(`^${label}$`) }) });
    await expect(ticket.locator('.ticket-environment')).toHaveText('Paper');
    await expect(summary.locator('.ticket-order-line')).toHaveText('Buy 1 SPY · Market');
    await expect(summary.locator('.ticket-total')).toContainText('$101.20');
    await expect(summary.locator('.ticket-quote-line')).toHaveText('Spread $0.02 · Quote 0s');
    await expect(row('Available capital')).toContainText('$100,000.00');
    await expect(row('Position after fill')).toContainText('0 → 1 share');
    await expect(ticket.locator('select')).toHaveCount(0);
    const duration = ticket.getByRole('group', { name: 'Duration', exact: true });
    const sessions = ticket.getByRole('group', { name: 'Trading sessions', exact: true });
    await expect(duration.getByRole('button', { name: 'Day', exact: true })).toHaveAttribute('aria-pressed', 'true');
    await expect(sessions.getByRole('button', { name: 'Regular', exact: true })).toHaveAttribute('aria-pressed', 'true');
    await expect(sessions.getByRole('button', { name: '+ Extended', exact: true })).toBeDisabled();
    await expect(row('Paca reservations')).not.toBeVisible();
    await summary.locator('summary').click();
    await expect(row('Paca reservations')).toBeVisible();
    await summary.locator('summary').click();
    await ticket.getByRole('button', { name: 'Limit', exact: true }).click();
    await expect(ticket.getByLabel('Limit price', { exact: true })).toHaveValue('101.21');
    await ticket.getByLabel('Limit price', { exact: true }).fill('1.001');
    await expect(ticket.getByRole('alert')).toContainText('$0.01 increments');
    await expect(ticket.locator('.submit-order')).toBeDisabled();
    await ticket.locator('form').evaluate((form: HTMLFormElement) => form.requestSubmit());
    expect(broker.writes).toHaveLength(0);
    await ticket.getByLabel('Limit price', { exact: true }).fill('0.12345');
    await expect(ticket.getByRole('alert')).toContainText('$0.0001 increments');
    await ticket.getByLabel('Limit price', { exact: true }).fill('0.1234');
    await expect(summary.locator('.ticket-order-line')).toContainText('Limit $0.1234');
    await sessions.getByRole('button', { name: '+ Extended', exact: true }).click();
    await duration.getByRole('button', { name: 'GTC', exact: true }).click();
    await expect(summary.locator('.ticket-execution-line')).toHaveText('GTC · Regular + extended hours');
    await ticket.getByRole('button', { name: 'Market', exact: true }).click();
    await expect(sessions.getByRole('button', { name: 'Regular', exact: true })).toHaveAttribute('aria-pressed', 'true');
    await ticket.getByRole('button', { name: 'Limit', exact: true }).click();
    await expect(sessions.getByRole('button', { name: 'Regular', exact: true })).toHaveAttribute('aria-pressed', 'true');
    await sessions.getByRole('button', { name: '+ Extended', exact: true }).click();
    await ticket.getByRole('button', { name: 'Buy SPY', exact: true }).click();
    await expect(ticket.getByRole('status')).toContainText('Order acknowledged');
    expect(broker.writes[0].body).toMatchObject({ symbol: 'SPY', qty: '1', side: 'buy', limit_price: '0.1234', time_in_force: 'gtc', extended_hours: true });
    await expect(summary.locator('.ticket-execution-line')).toHaveText('GTC · Regular + extended hours');
    await expect(duration.getByRole('button', { name: 'GTC', exact: true })).toBeDisabled();
    expect(broker.errors).toEqual([]);
  });
}

test('limit defaults use the executable quote and preserve explicit edits and clearing', async ({ page }) => {
  const broker = new BrokerFixture(true); await broker.install(page); await broker.connected(page);
  const ticket = page.locator('.order-ticket');
  await ticket.getByRole('button', { name: 'Limit', exact: true }).click();
  const limit = ticket.getByLabel('Limit price', { exact: true });
  await expect(limit).toHaveValue('101.21');
  await limit.fill('99.25');
  await broker.advance(page, 5000);
  await expect(limit).toHaveValue('99.25');
  await limit.fill('');
  await broker.advance(page, 5000);
  await expect(limit).toHaveValue('');
  await ticket.getByRole('button', { name: 'Sell holdings', exact: true }).click();
  await expect(limit).toHaveValue('101.19');
  await limit.fill('102');
  await page.getByLabel('Chart ticker').fill('QQQ'); await page.getByRole('button', { name: 'Go to ticker' }).click();
  await expect(limit).toHaveValue('101.19');
  expect(broker.writes).toHaveLength(0); expect(broker.errors).toEqual([]);
});

test('quantity presets use capital after pending manual reservations', async ({ page }) => {
  const broker = new BrokerFixture(); broker.buyingPower = 1000; await broker.install(page); await broker.connected(page);
  const ticket = page.locator('.order-ticket');
  await ticket.getByRole('button', { name: 'Limit', exact: true }).click();
  await ticket.getByLabel('Limit price', { exact: true }).fill('101');
  await ticket.getByLabel('Quantity', { exact: true }).fill('6');
  await ticket.getByRole('button', { name: 'Buy SPY', exact: true }).click();
  await expect(ticket.getByRole('status')).toContainText('Order acknowledged');
  await page.getByLabel('Chart ticker').fill('QQQ'); await page.getByRole('button', { name: 'Go to ticker' }).click();
  await ticket.getByRole('button', { name: 'New order', exact: true }).click();
  await expect(ticket.getByRole('group', { name: 'Quantity presets' }).getByRole('button')).toHaveText(['3']);
  await ticket.getByRole('group', { name: 'Quantity presets' }).getByRole('button', { name: '3', exact: true }).click();
  await expect(ticket.getByRole('region', { name: 'Order summary', exact: true })).toContainText('Buy 3 QQQ');
  await expect(ticket.locator('dl > div').filter({ hasText: 'Available capital' })).toContainText('$394.00');
  await expect(ticket.locator('dl > div').filter({ hasText: 'Paca reservations' })).toContainText('$606.00');
  await ticket.getByRole('button', { name: 'Buy QQQ', exact: true }).click();
  await expect(ticket.getByRole('status')).toContainText('Order acknowledged');
  expect(broker.writes[1].body).toMatchObject({ symbol: 'QQQ', qty: '3', limit_price: '101.21', time_in_force: 'day', extended_hours: false });
  expect(broker.errors).toEqual([]);
});

test('full holding closes require review, DAY for fractions, and renewed review for changed inventory', async ({ page }) => {
  const broker = new BrokerFixture();
  broker.positions = [{ symbol: 'QQQ', qty: '1.234567891', avg_entry_price: '100', side: 'long' }];
  await broker.install(page); await broker.connected(page);
  const ticket = page.locator('.order-ticket');
  await page.getByRole('button', { name: 'Close holding', exact: true }).click();
  await expect(ticket.getByRole('heading')).toHaveText('Trade QQQ'); expect(broker.writes).toHaveLength(0);
  await expect(ticket.locator('dl > div').filter({ hasText: 'Position after fill' })).toContainText('1.234567891 → 0 shares');
  await ticket.getByRole('group', { name: 'Duration', exact: true }).getByRole('button', { name: 'GTC', exact: true }).click();
  await expect(ticket.getByRole('alert')).toContainText('Choose Day'); await expect(ticket.locator('.submit-order')).toBeDisabled();
  await ticket.getByRole('group', { name: 'Duration', exact: true }).getByRole('button', { name: 'Day', exact: true }).click();
  await ticket.getByRole('button', { name: 'Sell QQQ', exact: true }).click();
  const confirmation = ticket.getByRole('region', { name: 'Confirm order', exact: true });
  await expect(confirmation).toContainText('entire holding'); expect(broker.writes).toHaveLength(0);
  await confirmation.getByRole('button', { name: 'Edit order' }).click();
  await expect(confirmation).toHaveCount(0); expect(broker.writes).toHaveLength(0);
  await ticket.getByRole('button', { name: 'Sell QQQ', exact: true }).click();
  broker.positions[0].qty = '2.5';
  await confirmation.getByRole('button', { name: 'Confirm sell QQQ', exact: true }).click();
  await expect(ticket.getByRole('status')).toContainText('whole shares');
  expect(broker.writes).toHaveLength(0);
  await ticket.getByLabel('Quantity', { exact: true }).fill('2.5');
  await page.getByRole('button', { name: 'Reconcile account', exact: true }).click();
  await ticket.getByRole('button', { name: 'Sell QQQ', exact: true }).click();
  await expect(confirmation).toContainText('Sell 2.5 QQQ'); expect(broker.writes).toHaveLength(0);
  await confirmation.getByRole('button', { name: 'Confirm sell QQQ', exact: true }).click();
  await expect(ticket.getByRole('status')).toContainText('Order acknowledged');
  expect(broker.writes).toHaveLength(1);
  expect(broker.writes[0].body).toMatchObject({ symbol: 'QQQ', qty: '2.5', side: 'sell', time_in_force: 'day', extended_hours: false });
  expect(broker.errors).toEqual([]);
});

test('large live orders require confirmation while small live orders submit directly', async ({ page }) => {
  const broker = new BrokerFixture(); await broker.install(page); await broker.connect(page, 'live');
  const ticket = page.locator('.order-ticket');
  await ticket.getByLabel('Arm live manual trading for this session').check();
  await ticket.getByLabel('Quantity', { exact: true }).fill('100');
  await ticket.getByRole('button', { name: 'Buy SPY', exact: true }).click();
  const confirmation = ticket.getByRole('region', { name: 'Confirm order', exact: true });
  await expect(confirmation).toContainText('$10,000 or more'); expect(broker.writes).toHaveLength(0);
  await confirmation.getByRole('button', { name: 'Edit order' }).click();
  await ticket.getByLabel('Quantity', { exact: true }).fill('1');
  await ticket.getByRole('button', { name: 'Buy SPY', exact: true }).click();
  await expect(ticket.getByRole('status')).toContainText('Order acknowledged');
  await expect(confirmation).toHaveCount(0); expect(broker.writes).toHaveLength(1);
  await ticket.getByRole('button', { name: 'New order', exact: true }).click();
  await page.getByLabel('Chart ticker').fill('QQQ'); await page.getByRole('button', { name: 'Go to ticker' }).click();
  await ticket.getByLabel('Quantity', { exact: true }).fill('100');
  await ticket.getByRole('button', { name: 'Buy QQQ', exact: true }).click();
  await confirmation.getByRole('button', { name: 'Confirm buy QQQ', exact: true }).click();
  await expect(ticket.getByRole('status')).toContainText('Order acknowledged');
  expect(broker.writes).toHaveLength(2);
  expect(await stored(page, 'manualCommands')).toHaveLength(2);
  expect(broker.errors).toEqual([]);
});

test('quote age advances without fresh quotes and stale limit orders are blocked', async ({ page }) => {
  const broker = new BrokerFixture(true); await broker.install(page); await broker.connected(page);
  const ticket = page.locator('.order-ticket');
  await ticket.getByRole('button', { name: 'Limit', exact: true }).click();
  await ticket.getByLabel('Limit price', { exact: true }).fill('100');
  broker.quoteTimestamp = new Date(broker.now).toISOString();
  await broker.advance(page, 31_000);
  await expect(ticket.locator('.ticket-quote-line')).toContainText('31s · stale');
  await expect(ticket.locator('.submit-order')).toBeDisabled();
  await expect(ticket.getByRole('alert')).toContainText('fresh');
  expect(broker.writes).toHaveLength(0); expect(broker.errors).toEqual([]);
});
